FROM node:18-bookworm-slim

RUN npm i -g pnpm

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml tsconfig.json ./
RUN pnpm install --frozen-lockfile

COPY src ./src

EXPOSE 8080
CMD [ "pnpm", "start" ]